# Generated by Django 5.1 on 2024-09-01 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_request_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_service',
            name='address',
            field=models.CharField(default='No Address Provided', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request_service',
            name='service_hours',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
            preserve_default=False,
        ),
    ]
